"""
Author:     Simon Brown
Date:       2026-07-21

Description:
    Converts restaurant_reviews.txt into reviews.ts for HawkMaps.

    Workflow:
        restaurant_reviews.txt
                |
                v
        generate_reviews.py
                |
                v
        src/data/reviews.ts

    The script:
        - Reads restaurant review data
        - Extracts food locations from locations.ts
        - Matches reviews to location IDs
        - Generates TypeScript review objects
"""


from pathlib import Path
import re
from datetime import datetime



# ─────────────────────────────────────────────
# Extract food locations from locations.ts
# ─────────────────────────────────────────────

def extractFoodLocations(filepath):

    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    food_locations = {}

    # Find each location object
    objects = re.findall(r"\{(.*?)\}", content, re.DOTALL)

    for obj in objects:

        type_match = re.search(r"type:\s*'([^']+)'", obj)

        if not type_match or type_match.group(1) != "food":
            continue

        id_match = re.search(r"id:\s*(\d+)", obj)

        # Allow escaped apostrophes inside names
        name_match = re.search(
            r"name:\s*'((?:\\'|[^'])*)'",
            obj
        )

        if id_match and name_match:

            name = name_match.group(1).replace("\\'", "'").strip()

            food_locations[name] = int(id_match.group(1))

    return food_locations


# ─────────────────────────────────────────────
# Extract reviews from TXT source
# ─────────────────────────────────────────────

def extractReviews(filepath, food_locations):

    reviews = []

    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()


    # Find header dynamically
    header_index = None

    for index, line in enumerate(lines):

        if "Building" in line and "Rating" in line:
            header_index = index
            break


    if header_index is None:
        raise ValueError(
            "Could not find review header"
        )


    review_id = 1


    for line in lines[header_index + 1:]:

        line = line.strip()

        if not line:
            continue


        # Remove Excel quote artifacts
        while line.startswith(",") or line.startswith('"'):
            line = line[1:]


        data = line.split("\t")


        if len(data) != 5:
            print(
                f"Skipping malformed entry: {line}"
            )
            continue


        restaurant = data[0].strip()
        subject = data[1].strip()
        rating = data[2].strip()
        comment = data[3].strip().strip('"')
        date = data[4].strip()


        if restaurant not in food_locations:

            print(
                f"Warning: '{restaurant}' "
                "not found in locations.ts"
            )

            continue


        # Convert DD/MM/YYYY → YYYY-MM-DD
        try:
            date = datetime.strptime(
                date,
                "%d/%m/%Y"
            ).strftime("%Y-%m-%d")

        except ValueError:
            print(
                f"Warning: Invalid date '{date}'"
            )


        reviews.append(
            {
                "id": review_id,
                "locationId": food_locations[restaurant],
                "rating": int(rating),
                "subject": subject,
                "comment": comment,
                "date": date,
            }
        )


        review_id += 1


    return reviews


# ─────────────────────────────────────────────
# Write reviews.ts
# ─────────────────────────────────────────────

def writeReviewsTS(reviews, filepath):

    with open(filepath, "w", encoding="utf-8") as f:

        f.write(
"""/**
 * HawkMaps · src/data/reviews.ts
 *
 * AUTO-GENERATED FILE
 * Do not edit manually.
 *
 * Generated by scripts/generate_reviews.py
 */

export type Review = {
  id: number;
  locationId: number;
  rating: number;
  subject: string;
  comment: string;
  date: string;
};


export const reviews: Review[] = [
"""
        )


        for review in reviews:

            # Escape quotes for TypeScript strings
            subject = review["subject"].replace('"', '\\"')
            comment = review["comment"].replace('"', '\\"')


            f.write(
f"""  {{
    id: {review["id"]},
    locationId: {review["locationId"]},
    rating: {review["rating"]},
    subject: "{subject}",
    comment: "{comment}",
    date: "{review["date"]}"
  }},
"""
            )


        f.write("];\n")


# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────

def main():

    project_root = Path(__file__).resolve().parent.parent


    locations_file = (project_root/"src"/"data"/"locations.ts")

    reviews_input = (project_root/"src"/"data"/"restaurant_reviews.txt")

    reviews_output = (project_root/"src"/"data"/"reviews.ts")


    food_locations = extractFoodLocations(
        locations_file
    )

    print(
        f"Found {len(food_locations)} food locations"
    )


    reviews = extractReviews(
        reviews_input,
        food_locations
    )


    print(
        f"Processed {len(reviews)} reviews"
    )


    writeReviewsTS(
        reviews,
        reviews_output
    )


    print(
        f"Generated {reviews_output}"
    )


if __name__ == "__main__":
    main()