/**
 * HawkMaps · src/data/reviews.ts
 *
 * AUTO-GENERATED FILE
 * Do not edit manually.
 *
 * Generated by scripts/generate_reviews.py
 */

export type Review = {
  id: number;
  locationId: number;
  rating: number;
  subject: string;
  comment: string;
  date: string;
};


export const reviews: Review[] = [
  {
    id: 1,
    locationId: 17,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 2,
    locationId: 17,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 3,
    locationId: 17,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
  {
    id: 4,
    locationId: 22,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 5,
    locationId: 22,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 6,
    locationId: 22,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
  {
    id: 7,
    locationId: 23,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 8,
    locationId: 23,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 9,
    locationId: 23,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
  {
    id: 10,
    locationId: 24,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 11,
    locationId: 24,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 12,
    locationId: 24,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
  {
    id: 13,
    locationId: 26,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 14,
    locationId: 26,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 15,
    locationId: 26,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
  {
    id: 16,
    locationId: 27,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 17,
    locationId: 27,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 18,
    locationId: 27,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
  {
    id: 19,
    locationId: 28,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 20,
    locationId: 28,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 21,
    locationId: 28,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
  {
    id: 22,
    locationId: 29,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 23,
    locationId: 29,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 24,
    locationId: 29,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
  {
    id: 25,
    locationId: 30,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 26,
    locationId: 30,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 27,
    locationId: 30,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
  {
    id: 28,
    locationId: 31,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 29,
    locationId: 31,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 30,
    locationId: 31,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
  {
    id: 31,
    locationId: 32,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 32,
    locationId: 32,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 33,
    locationId: 32,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
  {
    id: 34,
    locationId: 33,
    rating: 5,
    subject: "Good",
    comment: "Great food, enjoyable atmosphere!",
    date: "2026-07-07"
  },
  {
    id: 35,
    locationId: 33,
    rating: 3,
    subject: "Okay",
    comment: "Food was okay, service could use improvement.",
    date: "2026-07-08"
  },
  {
    id: 36,
    locationId: 33,
    rating: 1,
    subject: "Poor",
    comment: "Incorrect order with late service.",
    date: "2026-07-09"
  },
];
